baseURL = "http://sbacha.net"
languageCode = "en-us"
title = "the ephemeral monograph"
theme = "tatsu"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'emacs'
    tabWidth = 2